version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: prod  # Uses prod stage
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend  # Uses prod stage (Nginx)
    ports:
      - "80:80"
    depends_on:
      - backend